const waterQuotes = [
  "Water is the driving force of all nature. - Leonardo da Vinci",
  "Your body is 70% water. Give it what it craves.",
  "Hydration is the foundation of energy.",
  "Drink water like your skin depends on it — because it does.",
  "A glass of water is a toast to your health.",
  "Stay hydrated, stay sharp.",
  "Water: the original energy drink.",
  "Your brain is 75% water. Feed it well.",
  "Every sip is a step toward feeling better.",
  "Clear water, clear mind.",
  "Hydration is self-care in its simplest form.",
  "You're not hungry, you're thirsty. Drink up.",
  "Water flushes toxins and fuels your cells.",
  "Feeling tired? Try water before coffee.",
  "Your kidneys will thank you for this glass.",
  "Consistent hydration = consistent energy.",
  "Small sips throughout the day beat one big gulp.",
  "Water is the cheapest medicine.",
  "Dehydration causes headaches. Prevention is free.",
  "Keep drinking — your future self is grateful.",
  "Hydrated skin glows. That's science.",
  "One more glass closer to your goal.",
  "Water helps your muscles recover faster.",
  "Think of water as liquid fuel for your body.",
  "Your metabolism works better when hydrated.",
  "Start every morning with water. Set the tone.",
  "Carry a bottle. Change a habit. Change a life.",
  "Every cell in your body is asking for water right now.",
  "Hydration supports your immune system too.",
  "You just invested in your health. Well done.",
  "Good hydration = better digestion.",
  "Water keeps your joints moving smoothly.",
  "That was a good decision. Keep going.",
  "Sipping consistently is better than gulping rarely.",
  "Your heart pumps better when you're hydrated.",
];

export function getRandomQuote(): string {
  return waterQuotes[Math.floor(Math.random() * waterQuotes.length)];
}
